# Generated by Django 4.2.5 on 2023-09-27 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_docente_webdocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.docente'),
        ),
    ]
